name: orion

on: [workflow_dispatch]

env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  MACHINE_ID: orion
  CI_ROOT: ${{ secrets.ORION_CI_ROOT }}  # Env. secret variable

jobs:
  authenticate:
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 10

    steps:
    - name: Checkout ci-workflows
      uses: actions/checkout@v3

    - name: Validate myapp user
      run: |
        scripts/validate_user.py -u ${{ github.actor }} -p myapp -d ${{ env.CI_ROOT }}

  myapp_workflow:
    needs: authenticate
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 100

    - name: Checkout myapp repository
      uses: actions/checkout@v3
      with:
        repository: myapp
        path: ${{ github.run_id }}/myapp
