name: orion

on:
  workflow_call:

env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  MACHINE_ID: orion
  CI_ROOT: ${{ secrets.ORION_CI_ROOT }}  # Env. secret variable

jobs:
  validate-user:
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 100

    steps:
    - name: Checkout ci-workflows
      uses: actions/checkout@v3
      with:
        repository: TerrenceMcGuinness-NOAA/ci-workflows


    - name: Validate user
      run: |
        scripts/validate_user.py -g ${{ github.actor }} -p ci-workflows -d ${{ env.CI_ROOT }}
